-- Introduce a dedicated `sessions` table so each session has a stable,
-- monotonic `serial_id` independent of the UUID `session_id`. The frontend
-- formats display IDs as `SES-####` over the integer; rendering the UUID
-- directly produced unusable output like `SES-c9d12fa8-…`.
--
-- The table is materialized (not a view) so trigger-driven `last_seen`
-- updates and the IDENTITY column give a stable numeric ID even as the
-- underlying ledger rows roll over.

CREATE TABLE IF NOT EXISTS sessions (
    session_id  TEXT PRIMARY KEY,
    serial_id   BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    first_seen  DOUBLE PRECISION NOT NULL,
    last_seen   DOUBLE PRECISION NOT NULL
);

CREATE INDEX IF NOT EXISTS sessions_last_seen_idx ON sessions (last_seen DESC);

-- Backfill from existing ledger rows in chronological order so older
-- sessions get the lower serial_ids. Skip the empty session_id "noise"
-- bucket; the API filter excludes it from listings too.
INSERT INTO sessions (session_id, first_seen, last_seen)
SELECT session_id, MIN(timestamp), MAX(timestamp)
  FROM ledger
 WHERE session_id <> ''
 GROUP BY session_id
 ORDER BY MIN(timestamp) ASC
    ON CONFLICT (session_id) DO NOTHING;

-- AFTER INSERT trigger keeps the table in sync. On the first appearance of
-- a session_id, a row is inserted (serial_id assigned automatically). On
-- subsequent inserts, last_seen advances to MAX(existing, new).
CREATE OR REPLACE FUNCTION sessions_upsert_from_ledger() RETURNS trigger AS $$
BEGIN
    IF NEW.session_id = '' THEN
        RETURN NEW;
    END IF;
    INSERT INTO sessions (session_id, first_seen, last_seen)
    VALUES (NEW.session_id, NEW.timestamp, NEW.timestamp)
    ON CONFLICT (session_id) DO UPDATE
       SET last_seen = GREATEST(sessions.last_seen, EXCLUDED.last_seen);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS sessions_upsert_trigger ON ledger;
CREATE TRIGGER sessions_upsert_trigger
    AFTER INSERT ON ledger
    FOR EACH ROW EXECUTE FUNCTION sessions_upsert_from_ledger();
